apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vedavid
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: vedavid-dashboards-rust-k8s-demo
    files:
      - quotation-service.yaml
      - service-latency.yaml
